SEED:
  - 0
CUDA_VISIBLE_DEVICES:
  - 1
  - 3
  - 4
EPOCHS:
  - 2
BATCH_SIZE:
  - 2
LR:
  - 3e-4
MIN_LR:
  - 3e-6
DATA_PATH:
  - "babel_datasets/reweighted_wnet_train_en_babel.pickle"
TEST_DATA_PATH:
  - "babel_datasets/reweighted_wnet_test_en_babel.pickle"
USING_PEFT:
  - True
MODEL_TYPE:
  - "Llama"
MODEL_CHECKPOINT:
  - "decapoda-research/llama-30b-hf"
DTYPE:
- "full"
LOG_PRED_EVERY:
- 100
DATA_PREPROC_STYLE:
- "reweighted_wnet_remove_all_from_labels"
QLORA:
- true
  