SEED:
  - 42
CUDA_VISIBLE_DEVICES:
  - 1
  - 2
  - 3
  - 4
  - 5
EPOCHS:
  - 2
BATCH_SIZE:
  - 2
LR:
  - 3e-4
MIN_LR:
  - 3e-6
DATA_PATH:
  - "babel_datasets/wnet_only/global_train_babel.pickle"
TEST_DATA_PATH:
  - "babel_datasets/wnet_only/global_test_babel.pickle"
USING_PEFT:
  - True
MODEL_TYPE:
  - "Auto"
MODEL_CHECKPOINT:
  - "bigscience/bloomz-7b1"
DTYPE:
- "full"
LOG_PRED_EVERY:
- 1000
DATA_PREPROC_STYLE:
- "wnet_mulilang"
QLORA:
- false
LOAD_PATH:
- null 