SEED:
  - 42
CUDA_VISIBLE_DEVICES:
  - 0
  - 1
EPOCHS:
  - 1
BATCH_SIZE:
  - 32
LR:
  - 3e-4
MIN_LR:
  - 3e-6
DATA_PATH:
  - "babel_datasets/v2_wnet_lemmas_train_no_semeval16.pickle"
TEST_DATA_PATH:
  - "babel_datasets/v2_wnet_lemmas_test.pickle"
USING_PEFT:
  - True
MODEL_TYPE:
  - "Llama"
MODEL_CHECKPOINT:
  - "meta-llama/Llama-2-7b-hf"
DTYPE:
- "half"
LOG_PRED_EVERY:
  - 100
DATA_PREPROC_STYLE:
- "wnet2_lemmas_clear"
QLORA:
- true
LOAD_PATH:
- null 
