SEED:
  - 42
CUDA_VISIBLE_DEVICES:
  - 1
EPOCHS:
  - 1
BATCH_SIZE:
  - 32
LR:
  - 3e-4
MIN_LR:
  - 3e-6
DATA_PATH:
  - "babel_datasets/v2_wnet_def_train.pickle"
TEST_DATA_PATH:
  - "babel_datasets/v2_wnet_def_test.pickle"
USING_PEFT:
  - True
MODEL_TYPE:
  - "Auto"
MODEL_CHECKPOINT:
  - "mistralai/Mistral-7B-Instruct-v0.1"
DTYPE:
- "half"
LOG_PRED_EVERY:
  - 100
DATA_PREPROC_STYLE:
- "wnet2_def_coma"
QLORA:
- true
LOAD_PATH:
- null 
