SEED:
  - 42
CUDA_VISIBLE_DEVICES:
  - 1
  - 3
  - 4
  - 5
  - 6
EPOCHS:
  - 2
BATCH_SIZE:
  - 12
LR:
  - 3e-4
MIN_LR:
  - 3e-6
DATA_PATH:
  - "babel_datasets/wnet_only/global_train_babel.pickle"
TEST_DATA_PATH:
  - "babel_datasets/wnet_only/global_test_babel.pickle"
USING_PEFT:
  - True
MODEL_TYPE:
  - "Llama"
MODEL_CHECKPOINT:
  - "meta-llama/Llama-2-7b-hf"
DTYPE:
- "half"
LOG_PRED_EVERY:
- 1000
DATA_PREPROC_STYLE:
- "wnet_mulilang_instruct"
QLORA:
- true
LOAD_PATH:
- null 