SEED:
  - 0
CUDA_VISIBLE_DEVICES:
  - 1
  - 2
  - 3
  - 4
  - 5
EPOCHS:
  - 4
BATCH_SIZE:
  - 8
LR:
  - 3e-4
MIN_LR:
  - 3e-6
DATA_PATH:
  - "babel_datasets/global_train_ru_babel.pickle"
TEST_DATA_PATH:
  - "babel_datasets/global_test_ru_babel.pickle"
USING_PEFT:
  - True
MODEL_TYPE:
  - Auto
MODEL_CHECKPOINT:
  - "ai-forever/mGPT"
DTYPE:
- "full"
LOG_PRED_EVERY:
- 400
  