SEED:
  - 0
CUDA_VISIBLE_DEVICES:
  - 1
  - 2
  - 3
  - 4
  - 5
EPOCHS:
  - 4
BATCH_SIZE:
  - 6
LR:
  - 3e-4
MIN_LR:
  - 3e-6
DATA_PATH:
  - "babel_datasets/reweighted_wnet_train_en_babel.pickle"
TEST_DATA_PATH:
  - "babel_datasets/reweighted_wnet_test_en_babel.pickle"
USING_PEFT:
  - True
MODEL_TYPE:
  - Auto
MODEL_CHECKPOINT:
  - "EleutherAI/gpt-neo-1.3B"
DTYPE:
- "full"
LOG_PRED_EVERY:
- 800
DATA_PREPROC_STYLE:
- "reweighted_wnet_remove_all_from_labels"
  