SEED:
  - 57
SAVING_DIR:
  - "/home/data/taxonomy/"
CUDA_VISIBLE_DEVICES:
  - 1
BATCH_SIZE:
  - 32
INPUT_PATH:
  - "./data/MAG_CS/all.edgelist"
OUTPUT_PATH:
  - "./data/MAG_CS/embeddings/embeddings_ft.pickle"
MODEL_TYPE:
  - "FastText"
MODEL_CHECKPOINT:
  - '/home/data/taxonomy/cc.en.300.bin' #FT = /home/data/taxonomy/cc.en.300.bin
