DATA:
  - "environment"
IN_NAME:
  - './data/env/eurovoc/pred_hypernym/lemmas_ppl_clear.pickle'
COMPARE_NAME:
  - './data/env/eurovoc/mix_nodes/lemmas_clear.pickle'
N_PARENTS:
  - 2
ENABLE_MIXING:
  - false
LEMMA:
  - true
REVERSE:
  - true
LOW:
  - 0.1
HIGH:
  - 4
STEP:
  - 0.01
