DATA:
  - "science"
IN_NAME:
  - './data/sci/pred_hypernym/lemmas_ppl_clear.pickle'
COMPARE_NAME:
  - './data/sci/mix_nodes/lemmas_clear.pickle'
N_PARENTS:
  - 3
ENABLE_MIXING:
  - False
LEMMA:
  - true
REVERSE:
  - true
LOW:
  - 0.1
HIGH:
  - 4
STEP:
  - 0.1
