DATA:
  - "science"
IN_NAME:
  - './data/sci/pred_hypernym/lemmas_ppl_clear.pickle'
COMPARE_NAME:
  - './data/sci/mix_nodes/lemmas_clear.pickle'
INSERTIONS_PATH:
  - './data/sci/insertions/lemmas_ppl.pickle'
HYPO_PATH:
  - './data/sci/leaf_no_leafs/lemmas_ppl_clear.pickle'
N_PARENTS:
  - 2
ENABLE_MIXING:
  - True
RESOLVE_CONFLICTS:
  - True
USE_INSERTION_CONFLICT:
  - True
LEMMA:
  - true
REVERSE:
  - true
LOW:
  - 1.5
HIGH:
  - 3
STEP:
  - 0.1
