DATA:
  - "science"
IN_NAME:
  - '/home/LLM_Taxonomy/TExEval-2_testdata_1.2/data/sci/pred_hypernym/unified_clean_lemmas_ppl.pickle'
COMPARE_NAME:
  - './data/sci/mix_nodes/lemmas_clear.pickle'
INSERTIONS_PATH:
  - './data/sci/insertions/lemmas_ppl.pickle'
HYPO_PATH:
  - './data/sci/leaf_no_leafs/lemmas_ppl_clear.pickle'
N_PARENTS:
  - 2
ENABLE_MIXING:
  - False
RESOLVE_CONFLICTS:
  - False
USE_INSERTION_CONFLICT:
  - False
LEMMA:
  - true
REVERSE:
  - true
LOW:
  - 1
HIGH:
  - 5
STEP:
  - 0.01
