DATA:
  - "science"
IN_NAME:
  - '/Users/eneminova/LLM_Taxonomy/TExEval-2_testdata_1.2/data/sci/pred_hypernym/lemmas_ppl_clear.pickle'
COMPARE_NAME:
  - '/Users/eneminova/LLM_Taxonomy/TExEval-2_testdata_1.2/data/sci/pred_hypernym/lemmas_ppl_clear.pickle'
LEMMA:
  - true
REVERSE:
  - true
LOW:
  - 0.1
HIGH:
  - 30
STEP:
  - 0.01
