SEED:
  - 42
CUDA_VISIBLE_DEVICES:
  - 1
BATCH_SIZE:
  - 64
MODEL_CHECKPOINT:
  - "VityaVitalich/llama2-7b-hf-4b-lora-wnet2-lemmas-no-eurovoc"
OUT_NAME:
  - 'data/sci/mix_nodes/lemmas_clear.pickle'
IN_NAME:
  - 'data/sci/raw_pairs/mix_nodes_lemmas.pickle'
LOAD:
  - false
USE_DEF:
  - true
