SEED:
  - 57
CUDA_VISIBLE_DEVICES:
  - 1
BATCH_SIZE:
  - 64
MODEL_CHECKPOINT:
  - "VityaVitalich/llama2-7b-hf-4b-lora-wnet_verb"
OUT_NAME:
  - '/home/LLM_Taxonomy/LexicalEntailment/data/ant_pairs_formated_ppls.pickle'
IN_NAME:
  - '/home/LLM_Taxonomy/LexicalEntailment/data/ant_pairs_formated.pickle'
LOAD:
  - false
USE_DEF:
  - false
CASE:
  - "pred_hypernym"
