SEED:
  - 57
CUDA_VISIBLE_DEVICES:
  - 0
BATCH_SIZE:
  - 32
MODEL_CHECKPOINT:
  - "VityaVitalich/llama2-7b-hf-4b-lora-wnet_verb_def"
OUT_NAME:
  - '/home/LLM_Taxonomy/LexicalEntailment/data/ant_pairs_formated_def_ppls.pickle'
IN_NAME:
  - '/home/LLM_Taxonomy/LexicalEntailment/data/ant_pairs_formated_def.pickle'
LOAD:
  - false
USE_DEF:
  - true
CASE:
  - "pred_hypernym"
