SEED:
  - 42
CUDA_VISIBLE_DEVICES:
  - 1
BATCH_SIZE:
  - 64
MODEL_CHECKPOINT:
  - "VityaVitalich/llama2-7b-hf-4b-lora-wnet2-numbers-no-eurovoc"
OUT_NAME:
  - 'data/food/wordnet/pred_hypernym/numbers_clear.pickle'
IN_NAME:
  - 'data/food/wordnet/raw_pairs/pred_hypernym_numbers.pickle'
LOAD:
  - false
USE_DEF:
  - false
