SEED:
  - 57
CUDA_VISIBLE_DEVICES:
  - 3
BATCH_SIZE:
  - 16
MODEL_CHECKPOINT:
  - "VityaVitalich/Unified_Taxo"
OUT_NAME:
  - '/home/LLM_Taxonomy/LexicalEntailment/data/hyperlex_pairs_ppl.pickle'
IN_NAME:
  - '/home/LLM_Taxonomy/LexicalEntailment/data/hyperlex_pairs.pickle'
LOAD:
  - false
USE_DEF:
  - true
CASE:
  - "pred_hypernym"
