SEED:
  - 42
CUDA_VISIBLE_DEVICES:
  - 1
BATCH_SIZE:
  - 64
MODEL_CHECKPOINT:
  - "VityaVitalich/llama2-7b-hf-4b-lora-wnet2-lemmas-no-eurovoc"
OUT_NAME:
  - 'data/env/eurovoc/insertions/lemmas_ppl.pickle'
IN_NAME:
  - 'data/env/eurovoc/raw_pairs/insertions_lemmas.pickle'
LOAD:
  - false
USE_DEF:
  - true
CASE:
  - "simple_triplet_grandparent"
