SEED:
  - 57
CUDA_VISIBLE_DEVICES:
  - 0
EPOCHS:
  - 0
BATCH_SIZE:
  - 2
LR:
  - 3e-4
MIN_LR:
  - 3e-4
DATA_PATH:
  - "/home/LLM_Taxonomy/SemEval2018-Task9/custom_datasets/1B.italian.pickle"
TEST_DATA_PATH:
  - "/home/LLM_Taxonomy/SemEval2018-Task9/custom_datasets/1B.italian.pickle"
USING_PEFT:
  - True
MODEL_TYPE:
  - "Llama"
MODEL_CHECKPOINT:
  - "meta-llama/Llama-2-7b-hf"
DTYPE:
- "half"
LOG_PRED_EVERY:
- 400
DATA_PREPROC_STYLE:
- "1B_ablate_Unified_3beams_20topk_1temp_0norepeat"
LOAD_PATH:
- "meta-llama-Llama-2-7b-hfUnified_wn_noun_verb_def_epoch=0_MAP=0.7340136054421769.pth"
PREV_PREDICT:
- null
STRATEGY:
- "stohastic"
NUM_BEAMS:
- 1
MAX_NEW_TOKENS:
- 8
TEMPERATURE:
- 1
TOP_K:
- 20
NUM_RETURN_SEQUENCES:
- 2
NO_REPEAT_NGRAM:
- 0
QLORA:
- true
USE_DEF_PROMPT:
- false
USE_DEF_TARGET:
- false
USE_NUMBER_TARGET:
- false
SAVE_PATH:
- 'ablation_metrics/1B_ablate_few_shot.pickle'
FEW_SHOT_PATTERN:
- '/home/LLM_Taxonomy/SemEval2018-Task9/few_shots/italian*'
