SEED:
  - 57
CUDA_VISIBLE_DEVICES:
  - 0
EPOCHS:
  - 0
BATCH_SIZE:
  - 8
LR:
  - 3e-4
MIN_LR:
  - 3e-4
DATA_PATH:
  - "/home/LLM_Taxonomy/SemEval2018-Task9/custom_datasets/2B.music.pickle"
TEST_DATA_PATH:
  - "/home/LLM_Taxonomy/SemEval2018-Task9/custom_datasets/2B.music.pickle"
USING_PEFT:
  - True
MODEL_TYPE:
  - "Llama"
MODEL_CHECKPOINT:
  - "meta-llama/Llama-2-7b-hf"
DTYPE:
- "half"
LOG_PRED_EVERY:
- 400
DATA_PREPROC_STYLE:
- "2B_ablate_Unified_3beams_20topk_1temp_0norepeat"
LOAD_PATTERN:
- "meta-llama-Llama-2-7b-hfUnified_wn_noun_verb_def_FT_2A_2bs_epoch=0_batch*"
PREV_PREDICT:
- null
STRATEGY:
- "stohastic"
NUM_BEAMS:
- 3
MAX_NEW_TOKENS:
- 32
TEMPERATURE:
- 1
TOP_K:
- 20
NUM_RETURN_SEQUENCES:
- 2
NO_REPEAT_NGRAM:
- 0
QLORA:
- true
USE_DEF_PROMPT:
- false
USE_DEF_TARGET:
- false
USE_NUMBER_TARGET:
- false
SAVE_PATH:
- '2B_ablate.pickle'

