SEED:
  - 57
CUDA_VISIBLE_DEVICES:
  - 1
EPOCHS:
  - 1
BATCH_SIZE:
  - 16
LR:
  - 3e-4
MIN_LR:
  - 3e-6
DATA_PATH:
  - "SemEval2018-Task9/custom_datasets/train_with_wnet.pickle"
TEST_DATA_PATH:
  - "SemEval2018-Task9/custom_datasets/2B.music.pickle"
USING_PEFT:
  - True
MODEL_TYPE:
  - "Llama"
MODEL_CHECKPOINT:
  - "meta-llama/Llama-2-7b-hf"
DTYPE:
- "half"
LOG_PRED_EVERY:
- 400
DATA_PREPROC_STYLE:
- "semeval18-en-wnet-2B-long-57seed"
LOAD_PATH:
- "meta-llama-Llama-2-7b-hfsemeval-2bs-2B-57seed_epoch=0_MAP=0.6050427022977023.pth"
PREV_PREDICT:
- null
STRATEGY:
- "stohastic"
NUM_BEAMS:
- 1
MAX_NEW_TOKENS:
- 32
TEMPERATURE:
- 1
TOP_K:
- 20
NUM_RETURN_SEQUENCES:
- 2
QLORA:
- true
USE_DEF_PROMPT:
- false
USE_DEF_TARGET:
- false
USE_NUMBER_TARGET:
- false

