SEED:
  - 57
CUDA_VISIBLE_DEVICES:
  - 0
EPOCHS:
  - 0
BATCH_SIZE:
  - 4
LR:
  - 3e-4
MIN_LR:
  - 3e-6
DATA_PATH:
  - "TaxonomyEnrichment/data/MAG_CS/train_hypernyms.pickle"
TEST_DATA_PATH:
  - "TaxonomyEnrichment/data/MAG_CS/test_hypernyms.pickle"
USING_PEFT:
  - True
MODEL_TYPE:
  - "Llama"
MODEL_CHECKPOINT:
  - "meta-llama/Llama-2-7b-hf"
DTYPE:
- "half"
LOG_PRED_EVERY:
- 400
DATA_PREPROC_STYLE:
- "Wnet+FT-32bs_8beams_top40k_norepeat0_0.9temp"
LOAD_PATH:
- "meta-llama-Llama-2-7b-hfTaxoEnrich_MAG_CS_epoch=0_MAP=0.32630385487528346.pth"
PREV_PREDICT:
- null
STRATEGY:
- "stohastic"
NUM_BEAMS:
- 8
MAX_NEW_TOKENS:
- 32
TEMPERATURE:
- 0.9
TOP_K:
- 40
NUM_RETURN_SEQUENCES:
- 2
NO_REPEAT_NGRAM:
- 3
QLORA:
- true
USE_DEF_PROMPT:
- false
USE_DEF_TARGET:
- false
USE_NUMBER_TARGET:
- false

