SEED:
  - 57
CUDA_VISIBLE_DEVICES:
  - 1
EPOCHS:
  - 1
BATCH_SIZE:
  - 8
LR:
  - 3e-4
MIN_LR:
  - 3e-6
DATA_PATH:
  - "SemEval2018-Task9/custom_datasets/train_with_wnet.pickle"
TEST_DATA_PATH:
  - "SemEval2018-Task9/custom_datasets/1A.english.pickle"
USING_PEFT:
  - True
MODEL_TYPE:
  - "Llama"
MODEL_CHECKPOINT:
  - "meta-llama/Llama-2-7b-hf"
DTYPE:
- "half"
LOG_PRED_EVERY:
- 400
DATA_PREPROC_STYLE:
- "semeval18-en-wnet-1A-long-42seed"
LOAD_PATH:
- "meta-llama-Llama-2-7b-hfsemeval-1A-57seed-2bs_epoch=0_MAP=0.33722003169669834.pth"
PREV_PREDICT:
- null
STRATEGY:
- "stohastic"
NUM_BEAMS:
- 8
MAX_NEW_TOKENS:
- 32
TEMPERATURE:
- 0.8
TOP_K:
- 10
NUM_RETURN_SEQUENCES:
- 2
QLORA:
- true
USE_DEF_PROMPT:
- false
USE_DEF_TARGET:
- false
USE_NUMBER_TARGET:
- false

