SEED:
  - 57
CUDA_VISIBLE_DEVICES:
  - 0
EPOCHS:
  - 0
BATCH_SIZE:
  - 8
LR:
  - 3e-4
MIN_LR:
  - 3e-4
DATA_PATH:
  - "/home/LLM_Taxonomy/DataConstructor/data/easy_hyper.pickle"
TEST_DATA_PATH:
  - "/home/LLM_Taxonomy/DataConstructor/data/easy_hyper.pickle"
USING_PEFT:
  - True
MODEL_TYPE:
  - "Llama"
MODEL_CHECKPOINT:
  - "meta-llama/Llama-2-7b-hf"
DTYPE:
- "half"
LOG_PRED_EVERY:
- 400
DATA_PREPROC_STYLE:
- "EasyTask_Unified_3beams_40topk_0.8temp_3norepeat"
LOAD_PATH:
- "meta-llama-Llama-2-7b-hfUnified_wn_noun_verb_def_epoch=0_MAP=0.7340136054421769.pth"
PREV_PREDICT:
- null
STRATEGY:
- "stohastic"
NUM_BEAMS:
- 3
MAX_NEW_TOKENS:
- 32
TEMPERATURE:
- 0.8
TOP_K:
- 40
NUM_RETURN_SEQUENCES:
- 2
NO_REPEAT_NGRAM:
- 3
QLORA:
- true
USE_DEF_PROMPT:
- true
USE_DEF_TARGET:
- false
USE_NUMBER_TARGET:
- false

