TEST_DATA_PATH:
  - "babel_datasets/v2_wnet_def_test.pickle"
OUTPUT_NAME:
  - "/home/data/taxonomy/model_outputs/_meta-llama-Llama-2-7b-hfwnet2_lemmas_clear_0"
SAVE_EXAMPLES:
  - false
SAVE_EXAMPLES_PATH:
  - "babel_datasets/model_examples/llama-lemmas-clear"
IDS_TO_USE:
  - "all"
