TEST_DATA_PATH:
  - "TaxonomyEnrichment/data/MAG_CS/test_hypernyms.pickle"
OUTPUT_NAME:
  - "/home/data/taxonomy/model_outputs/_meta-llama-Llama-2-7b-hfTaxoEnrich_MAG_CS_0"
SAVE_EXAMPLES:
  - true
SAVE_EXAMPLES_PATH:
  - "/home/LLM_Taxonomy/TaxonomyEnrichment/model_examples/llama7b-initital"
IDS_TO_USE:
  - "all"
