TEST_DATA_PATH:
  - "SemEval2018-Task9/custom_datasets/2B.music.pickle"
OUTPUT_NAME:
  - "/home/data/taxonomy/model_outputs/_meta-llama-Llama-2-7b-hfsemeval18-en-wnet-2B-long-57seed_stohastic_"
SAVE_EXAMPLES:
  - true
SAVE_EXAMPLES_PATH:
  - "/home/LLM_Taxonomy/SemEval2018-Task9/model_examples/llama-7b-wnet-long-mean-2b-57seed"
IDS_TO_USE:
  - "all"
