TEST_DATA_PATH:
  - "wnet/v2_wnet_def_test.pickle"
OUTPUT_NAME:
  - "/home/data/taxonomy/model_outputs/_gpt2GPT2_wn_v2_def_0"
SAVE_EXAMPLES:
  - true
SAVE_EXAMPLES_PATH:
  - "/home/LLM_Taxonomy/babel_datasets/model_examples/gpt2"
IDS_TO_USE:
  - "all"
