SEED:
  - 57
CUDA_VISIBLE_DEVICES:
  - 1
EPOCHS:
  - 1
BATCH_SIZE:
  - 2
LR:
  - 3e-4
MIN_LR:
  - 3e-4
DATA_PATH:
  - "SemEval2018-Task9/custom_datasets/1A.english_train.pickle"
TEST_DATA_PATH:
  - "SemEval2018-Task9/custom_datasets/1A.english.pickle"
USING_PEFT:
  - True
MODEL_TYPE:
  - "Llama"
MODEL_CHECKPOINT:
  - "meta-llama/Llama-2-7b-hf"
DTYPE:
- "half"
LOG_PRED_EVERY:
  - 100
DATA_PREPROC_STYLE:
- "semeval-1A-57seed-2bs"
QLORA:
- true
LOAD_PATH:
- meta-llama-Llama-2-7b-hfonly-wnet-57seed-32bs_epoch=0_MAP=0.23933677520010854.pth
USE_DEF_PROMPT:
- false
USE_DEF_TARGET:
- false
USE_NUMBER_TARGET:
- false
