SEED:
  - 57
CUDA_VISIBLE_DEVICES:
  - 1
EPOCHS:
  - 1
BATCH_SIZE:
  - 32
LR:
  - 3e-4
MIN_LR:
  - 3e-4
DATA_PATH:
  - "TaxonomyEnrichment/data/verb/train_hypernyms_multisense_def.pickle"
TEST_DATA_PATH:
  - "TaxonomyEnrichment/data/verb/test_hypernyms_def.pickle"
USING_PEFT:
  - True
MODEL_TYPE:
  - "Llama"
MODEL_CHECKPOINT:
  - "meta-llama/Llama-2-7b-hf"
DTYPE:
- "half"
LOG_PRED_EVERY:
  - 100
DATA_PREPROC_STYLE:
- "TaxoEnrich_verb_multisense_32bs_3e-4_no-pretrain"
QLORA:
- true
LOAD_PATH:
- null #meta-llama-Llama-2-7b-hfonly-wnet-57seed-32bs_epoch=0_MAP=0.23933677520010854.pth
USE_DEF_PROMPT:
- false
USE_DEF_TARGET:
- false
USE_NUMBER_TARGET:
- false
