SEED:
  - 57
CUDA_VISIBLE_DEVICES:
  - 0
EPOCHS:
  - 1
BATCH_SIZE:
  - 32
LR:
  - 3e-4
MIN_LR:
  - 3e-5
DATA_PATH:
  - "wnet/unified_wnet_noun_verb_def_train.pickle"
TEST_DATA_PATH:
  - "wnet/unified_wnet_noun_verb_def_test.pickle"
USING_PEFT:
  - True
MODEL_TYPE:
  - "Llama"
MODEL_CHECKPOINT:
  - "meta-llama/Llama-2-7b-hf"
DTYPE:
- "half"
LOG_PRED_EVERY:
  - 100
DATA_PREPROC_STYLE:
- "Unified_wn_noun_verb_def"
QLORA:
- true
LOAD_PATH:
- null #meta-llama-Llama-2-7b-hfTaxoEnrich_noun_32bs_3e-4_no-pretrain_def_epoch=0_MAP=0.962030456852792.pth
USE_DEF_PROMPT:
- true
USE_DEF_TARGET:
- false
USE_NUMBER_TARGET:
- false
