SEED:
  - 57
CUDA_VISIBLE_DEVICES:
  - 0
  - 2
  - 3
EPOCHS:
  - 1
BATCH_SIZE:
  - 2
ACCUMULATION_STEPS: 
  - 16
LR:
  - 3e-5
MIN_LR:
  - 3e-6
DATA_PATH:
  - "/home/data/v.moskvoretskii/LLM_Taxonomy/taxollama3/taxollama3_train.pickle"
TEST_DATA_PATH:
  - "/home/data/v.moskvoretskii/LLM_Taxonomy/taxollama3/taxollama3_test.pickle"
USING_PEFT:
  - False
MODEL_TYPE:
  - "Auto"
MODEL_CHECKPOINT:
  - "VityaVitalich/Llama3-8b"
DTYPE:
- "half"
LOG_PRED_EVERY:
  - 100
DATA_PREPROC_STYLE:
- "test_taxo3"
QLORA:
- false
LOAD_PATH:
- null
USE_DEF_PROMPT:
- true
USE_DEF_TARGET:
- false
USE_NUMBER_TARGET:
- false
