SEED:
  - 57
CUDA_VISIBLE_DEVICES:
  - 1
EPOCHS:
  - 1
BATCH_SIZE:
  - 8
LR:
  - 3e-4
MIN_LR:
  - 3e-4
DATA_PATH:
  - "TaxonomyEnrichment/data/psychology/train_hypernyms_def.pickle"
TEST_DATA_PATH:
  - "TaxonomyEnrichment/data/psychology/test_hypernyms_def.pickle"
USING_PEFT:
  - True
MODEL_TYPE:
  - "Llama"
MODEL_CHECKPOINT:
  - "meta-llama/Llama-2-7b-hf"
DTYPE:
- "half"
LOG_PRED_EVERY:
  - 100
DATA_PREPROC_STYLE:
- "TaxoEnrich_MAG-PSY_def_8bs_3e-4_def_pretrain"
QLORA:
- true
LOAD_PATH:
- meta-llama-Llama-2-7b-hfTaxoEnrich_noun_32bs_3e-4_no-pretrain_def_epoch=0_MAP=0.962030456852792.pth
USE_DEF_PROMPT:
- true
USE_DEF_TARGET:
- false
USE_NUMBER_TARGET:
- false
